### ISSUE TITLE
Binding an IAM role to a GROUP doesn’t correctly attach the role to the group

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/terraform-provider-kestra#119]
To reproduce:

Create a binding of an Admin role to a group:
```yaml
resource "kestra_binding" "example" {
  type        = "GROUP"
  external_id = "68xAawPfiJPkTkZJIPX6jQ"
  role_id     = "3kcvnr27ZcdHXD2AUvIe7z"
  namespace   = "io.kestra.mynamespace"
}
```
https://kestra.io/docs/terraform/resources/binding

Then log in with a user who has that group attached and try to view Flows -> you will not see any flows.

However, when you attach the same Admin role to a group via UI, everything works. So it really seems like a terraform provider issue on that resource.

**Comment by brian-mulier-p** [comment]
Can't reproduce the issue. Ran on Kestra v0.17.8 & provider 0.17.1. If you manage to reproduce it under this version and provide a clear reproducer I can have a look but right now I see flows as intended with the above snippet

**Comment by anna-geller** [comment]
we couldn't reproduce so closing for now
