### ISSUE TITLE
Modification to namespace file in nested folder deletes other files in nested folder

### ISSUE THREAD

**Issue by japerry911** [kestra-io/terraform-provider-kestra#131]
### Expected Behavior

1. Terraform apply creates two namespaces in the same folder
2. Namespace 1 is changed
3. Terraform apply runs and says 1 create, 1 destroy on changed namespace
4. new file is recreated as expected, other file still exists exactly the same

### Actual Behaviour

1. Terraform apply creates two namespaces in the same folder
2. Namespace 1 is changed
3. Terraform apply runs and says 1 create, 1 destroy on changed namespace
4. it delete the file, and remakes it, but other file also gets deleted

### Steps To Reproduce

```hcl
terraform {
  required_providers {
    kestra = {
      source  = "kestra-io/kestra"
      version = "0.18.2"
    }
  }
}

# ---Automation.Measurement Namespace Files---
resource "kestra_namespace_file" "automations_namespace_file_ga4_gtm_name_checker_rows" {
  namespace = var.automations_measurement_namespace_id
  filename  = "ga4_gtm_name_checker_rows.sql"
  content   = file("${path.module}/content/automation/measurement/queries/ga4_gtm_name_checker_rows.sql")
}

resource "kestra_namespace_file" "automations_namespace_file_ga4_fetch_measurements_filtered" {
  namespace = var.automations_measurement_namespace_id
  filename  = "fetch_measurements_filtered.sql"
  content   = file("${path.module}/content/automation/measurement/queries/fetch_measurements_filtered.sql")
}

```

modify one of the above input files, and it will remove the other existing file. I think it deletes/recreates folder, and the other file gets lost.

### Environment Information

- Kestra Version: 0.19.1 ||| Terraform version -  v0.18.2 
- Operating System (OS / Docker / Kubernetes): cloud 
- Java Version (If not docker): n/a

**Comment by japerry911** [comment]
Hey @Skraye , sorry I missed this reply.

Thank you for looking into this.

Originally I thought that having nested folders in a Namespace would be useful, so the example you provided would be `filename = "folder1/file1.py"`, or something. 

But now I realize after getting more experience in Namespace Files, I don't think I want to add subfolders in a namespace, as I think it's overcomplexity.

You may close this, sorry to send you down a rabbit hole, thank you for investigating it.

**Comment by Skraye** [comment]
Hey Jack, thank for the feedback!

Without reproducer I close it for now, but if one day you (or anyone else) change your mind and find a reproducer, feel free to re-open the issue!
