### ISSUE TITLE
Update namespace to match the current namespace object (e.g. worker group property is available in EE, but missing in our Terraform provider)

### ISSUE THREAD

**Issue by Skraye** [kestra-io/terraform-provider-kestra#132]
### Feature description

Namespace ressources miss some properties (ex; worker group)

See which one are missing and add them

**Comment by anna-geller** [comment]
this is a bit vague, worker group already exists:

![image](https://github.com/user-attachments/assets/ce500c3c-4c97-4b1c-8f28-3a4b41d59122)

also, why is it P0 critical, who asked about this?

**Comment by Skraye** [comment]
@anna-geller This is a terraform issue, the namespace mentioned in the issue is the terraform ressource

**Comment by anna-geller** [comment]
Gotcha, so Terraform is outdated with respect to changes we made in EE. P0 makes sense then as we should catch up, thanks a lot!

**Comment by anna-geller** [comment]
docs done here https://registry.terraform.io/providers/kestra-io/kestra/latest/docs/resources/namespace#worker_group-1 

just not released here yet https://kestra.io/docs/terraform/data-sources/namespace
